### PR TITLE
Fix for correct work with $resource.query

### PR DESCRIPTION
**Pull request by alexbarmin**
I think, it is just a bug.

### CODE REVIEW

**Comment by guylabs** [comment]
Hi Alex,

when you apply the interceptor we want the whole processed response and not just the `_embeddedItems` because if you have other properties inside the response they will be lost. So this is not a bug and it is the needed behavior. You also see that one test is failing which exactly tests this.

Why do you think this is a bug?

Thanks and regards,

Guy

**Comment by alexbarmin** [comment]
I have a simple application with Spring Boot + Spring Data JPA in backend with the following frontnend:

// app
var app = angular.module('homeis', [
    'ngResource',
...
    'spring-data-rest''ui.bootstrap'
])
    .config(function(..., SpringDataRestInterceptorProvider){
        SpringDataRestInterceptorProvider.apply();
        // a lot of other code
    })

// resource definition
app.factory('Taxonomy', function($resource){
    return $resource('/taxonomies/:id');
});

// controller
app.controller('TaxonomyIndexController', function($scope, Taxonomy){
    $scope.taxonomies = Taxonomy.query();
    // other code
});

Wihtout _embeddedItems there is an error: Error: [$resource:badcfg] Error in resource configuration for action `query`. Expected response to contain an array but got an object (Request: GET /taxonomies)

And it is right, array with items is in _embeddedItems property of preprocessResponse.

Server response is:
---
{
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/taxonomies{?page,size,sort}",
      "templated" : true
    }
  },
  "_embedded" : {
    "taxonomies" : [ {
      "title" : "654",
      "alias" : "654",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/taxonomies/1"
        }
      }
    } ]
  },
  "page" : {
    "size" : 20,
    "totalElements" : 1,
    "totalPages" : 1,
    "number" : 0
  }
}
---

May be something wrong with configuration, can you explain it to me?

**Comment by guylabs** [comment]
Hi Alex,

so it looks like it worked now?

Thanks and regards,

Guy

**Comment by alexbarmin** [comment]
Yes it is!

Thanks!

**Pull request closed without merging**
